name: 'github-action-for-slack-notification'
author: 'svikramjeet'
description: 'The github action to post message on slack'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: hash
  color: red
